name: Setup Node
description: Setup Node

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v3

    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: lts/*
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install
